version: '2'

name: old-but-gold
services:
  proxy:
    image: nginx:latest
    ports:
      - 8021:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - app
    restart: unless-stopped

  app:
    build: app
    networks:
      - internal
    restart: unless-stopped

  bot:
    build: bot
    environment:
      APPNAME: Bot
      APPURL: http://app:8020/
      APPURLREGEX: ^http://app:8020/.*
      APPLIMIT: 5
      APPLIMITTIME: 300000
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
