name: pewpewpew
services:
  challenge:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      args:
        FLAG: "ARKAV{pew_p3w_pew_pew_p3W_p3w_99}"
    working_dir: /home/pwn
    container_name: pewpewpew
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "8044:9999"
    entrypoint: /etc/init.sh
    init: true
    restart: always
