version: "3"

services:
  launcher:
    build:
      context: .
    ports:
      - "${PUBLIC_PORT}:8080"
    environment:
      - FLAG=${FLAG}
      # - DISABLE_TICKET=true
      - LAUNCHER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "1.0"
